config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get '/menu', to: 'food_items#index', as: 'menu'
  resources :food_items, except: [:show, :index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/delivery_guy.rb
class DeliveryGuy < User
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  has_many :order_items
  has_many :orders, through: :order_items
  # validates :name, :price, :photo, :category, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  has_many :food_items, through: :order_items

  belongs_to :user, class_name: "User", foreign_key: "user_id", optional: true
  belongs_to :delivery_guy, class_name: "User", foreign_key: "delivery_guy_id"

  enum status: { submitted: 0, approved: 1, delivered: 2, rejected: 3 }

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :food_item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :orders, foreign_key: [:user_id, :delivery_guy_id]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    # devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    food_items = FoodItem.all
    @sandwich = food_items.where(category: 'sandwich')
    @rolls = food_items.where(category: 'roll')
    @fries = food_items.where(category: 'fries')
    @starters = food_items.where(category: 'starters')
    @drinks = food_items.where(category: 'drinks')
  end

  def create

  end

  def new

  end

  def edit

  end

  def update

  end

  def destroy

  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper

  def logo?(path)
    current_page?(path) ? 'logo.png' : 'logo-red.png'
  end
end

app/views/food_items/index.html.erb
<%= render 'shared/navbar' %>


<%= tag.div id: :food_items, data: {sandwich: @sandwich.to_json, rolls: @rolls.to_json, fries: @fries.to_json, starters: @starters.to_json, drinks: @drinks.to_json  } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name='language' content='RU'>
    <link rel="canonical" href="<%= root_url %>" />
    <link rel="alternate" hreflang="ru" href="<%= root_url %>" />
    <title>DeliveryApp</title>
    <%= csrf_meta_tags %>

    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%# stylesheet_pack_tag 'application', media: 'all' %>
    <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<header>
    <div class="home-banner" style="background-image: linear-gradient(to right, rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path "big-tasty-landing.jpg" %>);">
        <%= render 'shared/navbar' %>
        <div class="home-banner__content">
            <h1 class="home-banner__text">
                <span class="home-banner__text-p1"> Любимый макдоналдс </span> <span class="home-banner__text-p2"> у вашей двери. </span>
            </h1>
            <%= link_to "Меню", menu_path, class: "home-banner__btn" %>
        </div>
    </div>
</header>

<main>
    <section class="best-service">
        <div class="text-center margin-bottom-lg">
            <h2 class="heading-secondary"> Лучшая служба доставки </h2>
        </div>
        <div class="my-container">
            <div class="row row-eq">
                <div class="card">
                    <%= image_tag 'car.png', class: "card__img" %>
                    <p class="card__like-btn card__like-btn-white"> Быстро </p>
                    <p class="card__text">
                        Мы доставим ваш заказ за 60 минут или мы вернем вам деньги
                    </p>
                </div>

                <div class="card card-red">
                    <%= image_tag 'burger.png', class: "card__img" %>
                    <p class="card__like-btn card-red__like-btn"> Вкусно </p>
                    <p class="card__text card-red__text">
                        Еда будет теплой и вкусной такой же, как и в самом макдоналдсе
                    </p>
                </div>

                <div class="card">
                    <%= image_tag 'credit.png', class: "card__img" %>
                    <p class="card__like-btn card__like-btn-white"> Удобно </p>
                    <p class="card__text">
                        Можно заплатить картой на сайте или наличными курьеру , как вам удобнее
                    </p>
                </div>
            </div>
        </div>
    </section>

    <section class="delivery">
        <div class="text-center margin-bottom-lg">
            <h2 class="heading-secondary"> КАК ПРОХОДИТ ЗАКАЗ </h2>
        </div>
        <div class="my-container">
            <div class="timeline">
                <div class="timeline__box">
                    <div class="timeline__item">
                        <div class="timeline__content">
                            <%= image_tag 'mouse-cursor.png', class: 'timeline__image' %>
                            <p class="timeline__text">
                                Оформите заказ на сайте и оплатите удобным вам способом
                            </p>
                        </div>
                    </div>

                    <div class="timeline__item">
                        <div class="timeline__content">
                            <%= image_tag 'shop-bag.png', class: 'timeline__image' %>
                                <p class="timeline__text">
                                     Мы получаем ваш заказ и забираем его с макдональса и везем к вам
                                </p>
                        </div>
                    </div>

                    <div class="timeline__item">
                        <div class="timeline__content">
                            <%= image_tag 'cutlery.png', class: 'timeline__image' %>
                                <p class="timeline__text">
                                    Вы получаете заказ и наслаждаетесь едой
                                </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="price">
        <div class="text-center margin-bottom-lg">
            <h2 class="heading-secondary"> Cтоймость доставки </h2>
        </div>

        <div class="price__box">
            <div class="card card-red price__card">
                <%= image_tag 'money.png', class: "card__img price__img" %>
                    <p class="card__like-btn card-red__like-btn price__like-btn"> 250 ₽ </p>
                    <p class="card__text card-red__text price__text">
                        Доставляем во все районы Воронежа
                    </p>
            </div>
        </div>
    </section>
</main>

<footer class="footer">
    <div class="my-container">
        <div class="footer__content">
            <%= image_tag 'logo-red.png', class: 'footer__img' %>
            <ul class="footer__list">
                <li class="footer__list-item"> <a href="#" class="footer__link"> О нас </a>  </li>
                <li class="footer__list-item"> <a href="#" class="footer__link"> Стоймость</a> </li>
                <li class="footer__list-item"> <a href="#" class="footer__link"> Доставка </a> </li>
            </ul>
            <div class="footer__social">
                <p class="footer__social-header">Соцсети</p>
                <div class="footer__social-list">
                    <a class="footer__social-list-item footer__social-facebook" href="#"> <i class="fab fa-facebook-square "></i> </a>
                    <a class="footer__social-list-item footer__social-instagram" href="#"> <i class="fab fa-instagram footer__social-links"></i> </a>
                    <a class="footer__social-list-item footer__social-vk" href="#"> <i class="fab fa-vk footer__social-links"></i> </a>
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/shared/_navbar.html.erb
<nav>
    <div class="<%= current_page?(root_path) ? "navbar-delivery" : "navbar-delivery navbar-delivery-white" %>">
        <!-- Logo -->
        <a href="/" class="navbar-delivery-brand">
            <%= image_tag logo?(root_path) %>
        </a>

        <!-- Right Navigation -->
        <div class="navbar-delivery-right hidden-xs hidden-sm">

            <a href="" class="navbar-delivery-item navbar-delivery-link">О нас</a>
            <a href="" class="navbar-delivery-item navbar-delivery-link">Доставка</a>
            <a href="" class="navbar-delivery-item navbar-delivery-link">Стоймость</a>
            <a href="" class="navbar-delivery-item navbar-delivery-link">Вход</a>
            <a href="" class="navbar-delivery-item navbar-delivery-link navbar-delivery-signup">Регистрация</a>

            <!-- Profile picture with dropdown list -->
            <div class="navbar-delivery-item">
                <div class="dropdown">
                    <ul class="dropdown-menu dropdown-menu-right navbar-delivery-dropdown-menu">
                        <li>
                            <a href="#">Profile</a>
                        </li>
                        <li>
                            <a href="#">Dashboard</a>
                        </li>
                        <li>
                            <a href="#">Log Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Dropdown appearing on mobile only -->
        <div class="navbar-delivery-item hidden-md hidden-lg">
            <div class="dropdown">
                <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
                <ul class="dropdown-menu dropdown-menu-right navbar-delivery-dropdown-menu">
                    <li>
                        <a href="#">Host</a>
                    </li>
                    <li>
                        <a href="#">Trips</a>
                    </li>
                    <li>
                        <a href="#">Messagese</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>